#!/bin/sh

timedatectl set-timezone Europe/Stockholm
echo "GDis" > /etc/hostname
cp gdis.dtbo /boot/overlays
cp mountusb /root
cp umountusb /root

mkdir /etc/lirc
cp lirc_options.conf /etc/lirc
chmod +x /root/pi4/mediaplayer/run.sh
apt-get update

apt-get install lirc python3-pip mpd mpc default-jdk shairport-sync minidlna i2c-tools python-dev python-smbus python3-mpd python-flask libfreetype6-dev libjpeg-dev build-essential -y --allow-unauthenticated

mv /etc/lirc/lircd.conf.dist /etc/lirc/lircd.conf
mv /etc/lirc/lircd.conf.d/devinput.lircd.conf /etc/lirc/lircd.conf.d/devinput.lircd.conf.dist
cp mpd.conf /etc/mpd.conf
cp lircrc /etc/lirc
cp alu.lircd.conf /etc/lirc/lircd.conf.d
cp lirc_options.conf /etc/lirc
cp minidlna.conf /etc/minidlna.conf
#cp ready.wav streamer.wav coaxial.wav optical.wav wifi.wav ethernet.wav /root
#cp shairport-sync.conf /etc/shairport-sync.conf
update-rc.d minidlna defaults
cp oled.service /etc/systemd/system
cp mediaplayer.service /etc/systemd/system
systemctl enable oled
systemctl enable mediaplayer

sed -i '/dtparam=audio=on/d' /boot/config.txt
sed -i '$ i dtoverlay=gdis' /boot/config.txt
sed -i '$ i dtparam=i2c_arm_baudrate=400000' /boot/config.txt
sed -i '$ i dtparam=i2c_arm=on' /boot/config.txt
sed -i '$ i dtparam=pwr_led_trigger=none' /boot/config.txt
sed -i '$ i dtparam=pwr_led_activelow=off' /boot/config.txt
sed -i '$ i dtoverlay=pi3-act-led' /boot/config.txt
sed -i '$ i dtparam=act-led-trigger=none' /boot/config.txt
sed -i '$ i dtoverlay=gpio-ir,gpio_pin=4' /boot/config.txt
#sed -i '$ i gpio=17=op,dl' /boot/config.txt
#sed -i '$ i gpio=5=op,dl' /boot/config.txt
sed -i '$ i i2c-dev' /etc/modules
sed -i '$ i python /root/pi3/app.py &' /etc/rc.local
sed -i '$ i bash /root/mountusb &' /etc/rc.local
sed -i '$ i irexec > /dev/null &' /etc/rc.local

echo
echo "---Insalling roon---"
sleep 3

cd /root
curl -O http://download.roonlabs.com/builds/roonbridge-installer-linuxarmv7hf.sh
chmod +x roonbridge-installer-linuxarmv7hf.sh
yes yes | ./roonbridge-installer-linuxarmv7hf.sh

echo
echo "---Installing OLED---"
sleep 3

python3 -m pip install --upgrade setuptools wheel
pip3 install --upgrade luma.oled
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

echo 
echo "##############################################"
echo                      REBOOT
echo "##############################################"
sleep 2

mv /root/pi4 /root/pi3

reboot

